[PHP] Update swoole

diff --git a/dockerfile/php-fpm/7.2/swoole/Dockerfile b/dockerfile/php-fpm/7.2/swoole/Dockerfile
--- a/dockerfile/php-fpm/7.2/swoole/Dockerfile
+++ b/dockerfile/php-fpm/7.2/swoole/Dockerfile
@@ -1,3 +1,4 @@
+# syntax=docker/dockerfile:experimental
 ARG PHP_VERSION=7.2.22
 
 FROM --platform=$TARGETPLATFORM khs1994/php:${PHP_VERSION}-cli-alpine
@@ -25,22 +26,28 @@ ENV SWOOLE_VERSION=4.4.7
 
 ARG ALPINE_URL=dl-cdn.alpinelinux.org
 
-RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
+RUN --mount=type=bind,from=php:7.2.22-alpine,source=/usr/local/bin,target=/opt/bin,rw \
+    sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
       && apk add --no-cache --virtual .pecl_build_deps $PHPIZE_DEPS \
-      && export extension_name=swoole
+      && export PATH=$PATH:/opt/bin \
+      && export extension_name=swoole \
       && cd /tmp \
       && curl -fsSL https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz \
            | tar -zxvf - \
       && cd swoole-src-${SWOOLE_VERSION} \
       && phpize \
       && ./configure \
+           --enable-sockets \
+           --enable-openssl \
+           --enable-http2 \
+           --enable-mysqlnd \
       && make \
       && make install \
-      && docker-php-ext-enable ${extension_name} || echo "pecl ${extension} install error" \
+      && docker-php-ext-enable ${extension_name} || echo "pecl ${extension_name} install error" \
       && rm -rf /usr/local/lib/php/doc/${extension_name} \
       && rm -rf /usr/local/lib/php/test/${extension_name} \
       && rm -rf /usr/local/include/php/ext/${extension_name} \
-      && strip --strip-all $(php-config --extension-dir)/${extension_name}.so ; \
+      && strip --strip-all $(php-config --extension-dir)/${extension_name}.so \
       && apk del --no-network --no-cache .pecl_build_deps \
       && rm -rf /tmp/* \
       && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/*
diff --git a/dockerfile/php-fpm/7.3/swoole/Dockerfile b/dockerfile/php-fpm/7.3/swoole/Dockerfile
--- a/dockerfile/php-fpm/7.3/swoole/Dockerfile
+++ b/dockerfile/php-fpm/7.3/swoole/Dockerfile
@@ -28,20 +28,29 @@ ARG ALPINE_URL=dl-cdn.alpinelinux.org
 
 RUN --mount=type=bind,from=php:7.3.9-alpine,source=/usr/local/bin,target=/opt/bin,rw \
     sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
-        && apk add --no-cache --virtual .pecl_build_deps $PHPIZE_DEPS \
-        && export PATH=$PATH:/opt/bin \
-        && for extension in $PECL_EXTENSION;do \
-             pecl install $extension \
-             && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error" \
-             && rm -rf /usr/local/lib/php/doc/$(echo ${extension} | cut -d '-' -f 1) \
-             && rm -rf /usr/local/lib/php/test/$(echo ${extension} | cut -d '-' -f 1) \
-             && rm -rf /usr/local/include/php/ext/$(echo ${extension} | cut -d '-' -f 1) \
-             && strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
-           done \
-        && apk del --no-network --no-cache .pecl_build_deps \
-        && rm -rf /tmp/* \
-        && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/* \
-        && rm -rf /usr/local/sbin
+      && apk add --no-cache --virtual .pecl_build_deps $PHPIZE_DEPS \
+      && export PATH=$PATH:/opt/bin \
+      && export extension_name=swoole \
+      && cd /tmp \
+      && curl -fsSL https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz \
+           | tar -zxvf - \
+      && cd swoole-src-${SWOOLE_VERSION} \
+      && phpize \
+      && ./configure \
+           --enable-sockets \
+           --enable-openssl \
+           --enable-http2 \
+           --enable-mysqlnd \
+      && make \
+      && make install \
+      && docker-php-ext-enable ${extension_name} || echo "pecl ${extension_name} install error" \
+      && rm -rf /usr/local/lib/php/doc/${extension_name} \
+      && rm -rf /usr/local/lib/php/test/${extension_name} \
+      && rm -rf /usr/local/include/php/ext/${extension_name} \
+      && strip --strip-all $(php-config --extension-dir)/${extension_name}.so \
+      && apk del --no-network --no-cache .pecl_build_deps \
+      && rm -rf /tmp/* \
+      && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/*
 
 WORKDIR /app
 
diff --git a/dockerfile/php-fpm/7.4/swoole/Dockerfile b/dockerfile/php-fpm/7.4/swoole/Dockerfile
--- a/dockerfile/php-fpm/7.4/swoole/Dockerfile
+++ b/dockerfile/php-fpm/7.4/swoole/Dockerfile
@@ -31,33 +31,29 @@ ARG ALPINE_URL=dl-cdn.alpinelinux.org
 
 RUN --mount=type=bind,from=php:7.4.0RC1-alpine,source=/usr/local/bin,target=/opt/bin,rw \
     sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
-        && apk add --no-cache --virtual .pecl_build_deps $PHPIZE_DEPS \
-        && export PATH=$PATH:/opt/bin \
-        && for extension in $PECL_EXTENSION;do \
-             pecl install $extension \
-             && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error" \
-             && rm -rf /usr/local/lib/php/doc/$(echo ${extension} | cut -d '-' -f 1) \
-             && rm -rf /usr/local/lib/php/test/$(echo ${extension} | cut -d '-' -f 1) \
-             && rm -rf /usr/local/include/php/ext/$(echo ${extension} | cut -d '-' -f 1) \
-             && strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
-           done \
-# https://github.com/tideways/php-xhprof-extension.git
-        && test `uname -m` = 'x86_64' \
-        && (cd /tmp \
-        && curl -fsSL https://github.com/tideways/php-xhprof-extension/archive/master.tar.gz \
+      && apk add --no-cache --virtual .pecl_build_deps $PHPIZE_DEPS \
+      && export PATH=$PATH:/opt/bin \
+      && export extension_name=swoole \
+      && cd /tmp \
+      && curl -fsSL https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz \
            | tar -zxvf - \
-        && cd php-xhprof-extension-master \
-        && phpize \
-        && ./configure \
-        && make \
-        && make install \
-        && docker-php-ext-enable tideways_xhprof \
-        && mv /usr/local/etc/php/conf.d/docker-php-ext-tideways_xhprof.ini \
-          /usr/local/etc/php/conf.d/docker-php-ext-tideways_xhprof.ini.default) \
-        || true \
-        && apk del --no-network --no-cache .pecl_build_deps \
-        && rm -rf /tmp/* \
-        && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/*
+      && cd swoole-src-${SWOOLE_VERSION} \
+      && phpize \
+      && ./configure \
+           --enable-sockets \
+           --enable-openssl \
+           --enable-http2 \
+           --enable-mysqlnd \
+      && make \
+      && make install \
+      && docker-php-ext-enable ${extension_name} || echo "pecl ${extension_name} install error" \
+      && rm -rf /usr/local/lib/php/doc/${extension_name} \
+      && rm -rf /usr/local/lib/php/test/${extension_name} \
+      && rm -rf /usr/local/include/php/ext/${extension_name} \
+      && strip --strip-all $(php-config --extension-dir)/${extension_name}.so \
+      && apk del --no-network --no-cache .pecl_build_deps \
+      && rm -rf /tmp/* \
+      && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/*
 
 WORKDIR /app
 
diff --git a/dockerfile/php-fpm/nightly/swoole/Dockerfile b/dockerfile/php-fpm/nightly/swoole/Dockerfile
--- a/dockerfile/php-fpm/nightly/swoole/Dockerfile
+++ b/dockerfile/php-fpm/nightly/swoole/Dockerfile
@@ -25,29 +25,28 @@ ENV PECL_EXTENSION \
 ENV SWOOLE_VERSION=4.4.7
 
 RUN --mount=type=bind,from=php:alpine,source=/usr/local/bin,target=/opt/bin,rw \
-    --mount=type=cache,target=/usr/local/lib/php/test \
-    --mount=type=cache,target=/usr/local/lib/php/doc \
-      set -x \
-      && export PATH=$PATH:/opt/bin \
+    sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
       && apk add --no-cache --virtual .pecl_build_deps $PHPIZE_DEPS \
-      && curl -sfL -o /usr/local/bin/pickle \
-        https://github.com/khs1994-php/pickle/releases/download/v0.4.0-2019-02-14/pickle.phar \
-      && chmod +x /usr/local/bin/pickle \
-      && for extension in $PECL_EXTENSION;do \
-           EXT_REAL_NAME=$(echo ${extension} | cut -d '-' -f 1) \
-           && pickle install $extension -n --defaults \
-           || (cd /tmp/${EXT_REAL_NAME}/${EXT_REAL_NAME}* \
-           && phpize \
-           && ./configure \
-           && make \
-           && make install \
-           && rm -rf /tmp/${EXT_REAL_NAME}) \
-           && docker-php-ext-enable ${EXT_REAL_NAME} || echo "pecl ${extension} install error" \
-           && rm -rf /usr/local/include/php/ext/${EXT_REAL_NAME} \
-           && strip --strip-all $(php-config --extension-dir)/${EXT_REAL_NAME}.so || true ; \
-         done \
-         \
-      ; apk del --no-network --no-cache .pecl_build_deps \
+      && export PATH=$PATH:/opt/bin \
+      && export extension_name=swoole \
+      && cd /tmp \
+      && curl -fsSL https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz \
+           | tar -zxvf - \
+      && cd swoole-src-${SWOOLE_VERSION} \
+      && phpize \
+      && ./configure \
+           --enable-sockets \
+           --enable-openssl \
+           --enable-http2 \
+           --enable-mysqlnd \
+      && make \
+      && make install \
+      && docker-php-ext-enable ${extension_name} || echo "pecl ${extension_name} install error" \
+      && rm -rf /usr/local/lib/php/doc/${extension_name} \
+      && rm -rf /usr/local/lib/php/test/${extension_name} \
+      && rm -rf /usr/local/include/php/ext/${extension_name} \
+      && strip --strip-all $(php-config --extension-dir)/${extension_name}.so \
+      && apk del --no-network --no-cache .pecl_build_deps \
       && rm -rf /tmp/* \
       && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/*
 
