Release v18.02-rc2
Release v18.02-rc2 (#97)

diff --git a/cli/php-artisan b/cli/php-artisan
--- a/cli/php-artisan
+++ b/cli/php-artisan
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-if [ -f "khs1994-robot.enc" ];then echo -e "\n\033[32mINFO\033[0m  不允许在 bin 目录中执行"; exit 1; fi
+if [ -f "khs1994-robot.enc" ];then echo -e "\n\033[32mINFO\033[0m Can't EXEC in cli folder"; exit 1; fi
 
-. .env ; LARAVEL_PATH=$1 ; CMD="$2" ; ARCH=`uname -m`
+. .env; LARAVEL_PATH=$1; shift; CMD="$@"; ARCH=`uname -m`
 
 # 判断架构
 
