Update php image

diff --git a/dockerfile/php-fpm/5.6/alpine/Dockerfile b/dockerfile/php-fpm/5.6/alpine/Dockerfile
--- a/dockerfile/php-fpm/5.6/alpine/Dockerfile
+++ b/dockerfile/php-fpm/5.6/alpine/Dockerfile
@@ -50,10 +50,6 @@ ENV PECL_EXTENSION \
       xdebug-2.5.5 \
       yaml-1.3.1 \
       ${PECL_EXTENSION_EXTRA:-}
-      # swoole
-
-# 构建变量默认值为原始值，笔记本构建统一使用 docker-compose 构建
-# 国内镜像地址在 docker-compose.yml 中定义
 
 ARG ALPINE_URL=dl-cdn.alpinelinux.org
 
@@ -82,7 +78,6 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
                          libxpm \
                          ${APK_EXTRA:-} \
                          " \
-                         # libwebp \
                          # tidyhtml-libs \
       # *-dev 编译之后删除
       && PHP_FPM_BUILD_DEPS=" \
@@ -119,9 +114,15 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
                                     --with-xpm-dir=/usr \
         && docker-php-ext-install $PHP_EXTENSION \
         && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers \
-        && for extension in $PECL_EXTENSION;do \
+        && for extension in ${PHP_EXTENSION};do \
+             strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
+           done \
+        && for extension in ${PECL_EXTENSION};do \
              pecl install $extension \
-               && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error"; \
+             && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error" \
+             && rm -rf /usr/local/lib/php/doc/$(echo ${extension} | cut -d '-' -f 1) \
+             && rm -rf /usr/local/lib/php/test/$(echo ${extension} | cut -d '-' -f 1) \
+             && strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
            done \
         && docker-php-ext-enable opcache \
         && apk del --no-cache .build-deps .php-fpm-build-deps \
@@ -129,6 +130,7 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
         && mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
           /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.default \
         && rm -rf /tmp/* \
+        && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/* \
         # 创建日志文件夹
         && mkdir -p /var/log/php-fpm \
         && ln -sf /dev/stdout /var/log/php-fpm/access.log \
diff --git a/dockerfile/php-fpm/7.1/alpine/Dockerfile b/dockerfile/php-fpm/7.1/alpine/Dockerfile
--- a/dockerfile/php-fpm/7.1/alpine/Dockerfile
+++ b/dockerfile/php-fpm/7.1/alpine/Dockerfile
@@ -52,9 +52,6 @@ ENV PECL_EXTENSION \
       swoole \
       ${PECL_EXTENSION_EXTRA:-}
 
-# 构建变量默认值为原始值，笔记本构建统一使用 docker-compose 构建
-# 国内镜像地址在 docker-compose.yml 中定义
-
 ARG ALPINE_URL=dl-cdn.alpinelinux.org
 
 RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
@@ -77,7 +74,6 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
                          xmlrpc-c \
                          enchant \
                          c-client \
-                         libwebp \
                          icu-libs \
                          libxpm \
                          libwebp \
@@ -121,9 +117,15 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
                                     --with-xpm-dir=/usr \
         && docker-php-ext-install $PHP_EXTENSION \
         && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers \
+        && for extension in ${PHP_EXTENSION};do \
+             strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
+           done \
         && for extension in $PECL_EXTENSION;do \
              pecl install $extension \
-               && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error"; \
+             && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error" \
+             && rm -rf /usr/local/lib/php/doc/$(echo ${extension} | cut -d '-' -f 1) \
+             && rm -rf /usr/local/lib/php/test/$(echo ${extension} | cut -d '-' -f 1) \
+             && strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
            done \
         # https://github.com/tideways/php-xhprof-extension.git
         && cd /tmp \
@@ -142,6 +144,7 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
         && mv /usr/local/etc/php/conf.d/docker-php-ext-tideways_xhprof.ini \
           /usr/local/etc/php/conf.d/docker-php-ext-tideways_xhprof.ini.default \
         && rm -rf /tmp/* \
+        && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/* \
         # 创建日志文件夹
         && mkdir -p /var/log/php-fpm \
         && ln -sf /dev/stdout /var/log/php-fpm/access.log \
diff --git a/dockerfile/php-fpm/7.2/alpine/Dockerfile b/dockerfile/php-fpm/7.2/alpine/Dockerfile
--- a/dockerfile/php-fpm/7.2/alpine/Dockerfile
+++ b/dockerfile/php-fpm/7.2/alpine/Dockerfile
@@ -35,7 +35,7 @@ ENV PHP_EXTENSION \
       sysvmsg \
       sysvsem \
       sysvshm \
-# tidy \
+      # tidy \
       xmlrpc \
       xsl \
       zip \
@@ -49,11 +49,7 @@ ENV PECL_EXTENSION \
 # 安装测试版的扩展，可以在扩展名后加 -beta
       xdebug \
       yaml \
-      swoole \
       ${PECL_EXTENSION_EXTRA:-}
-
-# 构建变量默认值为原始值，笔记本构建统一使用 docker-compose 构建
-# 国内镜像地址在 docker-compose.yml 中定义
 
 ARG ALPINE_URL=dl-cdn.alpinelinux.org
 
@@ -77,7 +73,6 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
                          xmlrpc-c \
                          enchant \
                          c-client \
-                         libwebp \
                          icu-libs \
                          libxpm \
                          libwebp \
@@ -122,10 +117,16 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
                                         --with-webp-dir=/usr \
                                         --with-xpm-dir=/usr \
         && docker-php-ext-install $PHP_EXTENSION \
-        && apk add --no-cache --virtual .build-deps linux-headers $PHPIZE_DEPS \
+        && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
+        && for extension in ${PHP_EXTENSION};do \
+             strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
+           done \
         && for extension in $PECL_EXTENSION;do \
              pecl install $extension \
-               && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error"; \
+             && docker-php-ext-enable $(echo ${extension} | cut -d '-' -f 1) || echo "pecl ${extension} install error" \
+             && rm -rf /usr/local/lib/php/doc/$(echo ${extension} | cut -d '-' -f 1) \
+             && rm -rf /usr/local/lib/php/test/$(echo ${extension} | cut -d '-' -f 1) \
+             && strip --strip-all $(php-config --extension-dir)/$(echo ${extension} | cut -d '-' -f 1).so ; \
            done \
         # https://github.com/tideways/php-xhprof-extension.git
         && cd /tmp \
@@ -139,6 +140,7 @@ RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_URL}/g" /etc/apk/repositories \
         && docker-php-ext-enable opcache tideways_xhprof \
         && apk del --no-cache .build-deps .php-fpm-build-deps \
         && rm -rf /tmp/* \
+        && rm -rf /usr/local/lib/php/.registry/.channel.pecl.php.net/* \
         # 默认不启用 xdebug
         && mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
           /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.default \
